"""Tests for reading the document library back out of the index.

The inputs are copied exactly from pieces stored in the live index, so a change
to scripts/ingest.py's text layout breaks these rather than the Library tab.
"""

from services.orchestrator import library

DTC = {
    "doc_type": "dtc",
    "source_file": "dtc_codes.csv",
    "section": "P0420",
    "severity": "medium",
    "title": "P0420 - Catalyst System Efficiency Below Threshold (Bank 1)",
    "content": "Fault code P0420 (Powertrain): Catalyst System Efficiency Below Threshold (Bank 1).\n"
    "What it means: The catalytic converter is not cleaning the exhaust as well as it should.\n"
    "Common causes: Worn catalytic converter; failed rear oxygen sensor; exhaust leak; "
    "engine running rich or lean for a long time.\n"
    "Severity: medium. Safe to drive: yes-with-care.",
}

MAINT = {
    "doc_type": "maintenance",
    "source_file": "maintenance.csv",
    "section": "Brake fluid",
    "severity": "low",
    "content": "Maintenance item: Brake fluid.\n"
    "Replacement or service interval: every 40,000 km or every 24 months.\n"
    "Notes: Brake fluid absorbs moisture over time regardless of distance driven. "
    "Replace on time even if the car is barely used.\n"
    "Typical workshop time: 45 minutes.",
}


def tsb(section, text, page=1, number="TSB-010"):
    return {
        "doc_type": "bulletin",
        "source_file": f"{number}.pdf",
        "section": section,
        "page": page,
        "content": f"[{number}, section {section}] {text}",
    }


HEADER = tsb(
    "HEADER",
    "SERVICE BULLETIN TSB-010 Corvale S1 1.2L petrol — clutch pedal feeling spongy SYNTHETIC DOCUMENT. "
    "Generated by a language model for a portfolio project. Not a real bulletin.",
)


def test_a_fault_code_is_read_back_into_fields():
    c = library.fault_code(DTC)
    assert c["code"] == "P0420"
    assert c["system"] == "Powertrain"
    assert c["title"] == "Catalyst System Efficiency Below Threshold (Bank 1)"
    assert c["meaning"].startswith("The catalytic converter")
    assert c["causes"].endswith("for a long time")
    assert c["severity"] == "medium"
    assert c["safe_to_drive"] == "yes-with-care"


def test_the_citation_shown_matches_what_the_agent_writes():
    """The Library shows how the assistant cites each document, so it has to
    match retrieval.Chunk.citation() exactly."""
    assert library.fault_code(DTC)["cite_as"] == "fault code list, P0420"
    assert library.maintenance_item(MAINT)["cite_as"] == "maintenance schedule, Brake fluid"
    b = library.bulletins([HEADER, tsb("SYMPTOMS", "Pedal feels soft.")])[0]
    assert b["sections"][0]["cite_as"] == "TSB-010, Symptoms"


def test_a_maintenance_item_is_read_back_into_fields():
    m = library.maintenance_item(MAINT)
    assert m["item"] == "Brake fluid"
    assert m["interval"] == "every 40,000 km or every 24 months"
    assert m["notes"].startswith("Brake fluid absorbs moisture")
    assert m["workshop_minutes"] == 45


def test_a_bulletin_gets_its_number_vehicle_and_topic_from_the_header():
    b = library.bulletins([HEADER, tsb("SUMMARY", "A summary.")])[0]
    assert b["number"] == "TSB-010"
    assert b["vehicle"] == "Corvale S1 1.2L petrol"
    assert b["topic"] == "clutch pedal feeling spongy"


def test_the_header_is_not_shown_as_a_section():
    b = library.bulletins([HEADER, tsb("SUMMARY", "A summary.")])[0]
    assert [s["name"] for s in b["sections"]] == ["Summary"]


def test_sections_come_out_in_bulletin_order_whatever_order_the_index_returns():
    pieces = [
        tsb("WARRANTY INFORMATION", "w", page=2),
        tsb("SYMPTOMS", "s"),
        HEADER,
        tsb("SUMMARY", "a"),
        tsb("PARTS REQUIRED", "p", page=2),
    ]
    names = [s["name"] for s in library.bulletins(pieces)[0]["sections"]]
    assert names == ["Summary", "Symptoms", "Parts Required", "Warranty Information"]


def test_the_piece_label_is_stripped_from_section_text():
    b = library.bulletins([HEADER, tsb("SYMPTOMS", "Pedal feels soft.")])[0]
    assert b["sections"][0]["text"] == "Pedal feels soft."


def test_an_unknown_section_is_kept_not_dropped():
    b = library.bulletins([HEADER, tsb("SUMMARY", "a"), tsb("TORQUE SPECIFICATIONS", "t", page=2)])[0]
    assert [s["name"] for s in b["sections"]] == ["Summary", "Torque Specifications"]


def test_a_section_split_across_pieces_is_shown_as_one():
    b = library.bulletins([HEADER, tsb("REPAIR PROCEDURE", "first half"), tsb("REPAIR PROCEDURE", "second half")])[0]
    assert len(b["sections"]) == 1
    assert "first half" in b["sections"][0]["text"] and "second half" in b["sections"][0]["text"]


def test_a_bulletin_without_a_readable_header_still_appears():
    b = library.bulletins([tsb("SUMMARY", "a", number="TSB-031")])[0]
    assert b["number"] == "TSB-031"
    assert b["topic"] == ""


def test_build_groups_counts_and_sorts():
    pieces = [
        HEADER,
        tsb("SUMMARY", "a"),
        tsb("SUMMARY", "b", number="TSB-002"),
        DTC,
        {**DTC, "section": "P0010", "content": DTC["content"].replace("P0420", "P0010")},
        MAINT,
    ]
    lib = library.build(pieces)
    assert lib["counts"] == {"fault_codes": 2, "maintenance": 1, "bulletins": 2, "pieces": 6}
    assert [c["code"] for c in lib["fault_codes"]] == ["P0010", "P0420"]
    assert [b["number"] for b in lib["bulletins"]] == ["TSB-002", "TSB-010"]


def test_load_is_cached(monkeypatch):
    calls = []

    def fetch_all(fields, top=1000):
        calls.append((fields, top))
        return [DTC, MAINT, HEADER]

    monkeypatch.setattr(library.retrieval, "fetch_all", fetch_all)
    monkeypatch.setattr(library, "_cache", {"at": 0.0, "data": None})

    first = library.load()
    second = library.load()
    assert first is second
    assert len(calls) == 1
    assert first["counts"]["bulletins"] == 1
