"""Tests for reading the document library back out of the index.

The inputs are copied exactly from pieces stored in the live index, so a change
to scripts/ingest.py's text layout breaks these rather than the Library tab.
"""

import threading

import pytest

from services.orchestrator import library

DTC = {
    "doc_type": "dtc",
    "source_file": "dtc_codes.csv",
    "section": "P0420",
    "severity": "medium",
    "title": "P0420 - Catalyst System Efficiency Below Threshold (Bank 1)",
    "content": "Fault code P0420 (Powertrain): Catalyst System Efficiency Below Threshold (Bank 1).\n"
    "What it means: The catalytic converter is not cleaning the exhaust as well as it should.\n"
    "Common causes: Worn catalytic converter; failed rear oxygen sensor; exhaust leak; "
    "engine running rich or lean for a long time.\n"
    "Severity: medium. Safe to drive: yes-with-care.",
}

MAINT = {
    "doc_type": "maintenance",
    "source_file": "maintenance.csv",
    "section": "Brake fluid",
    "severity": "low",
    "content": "Maintenance item: Brake fluid.\n"
    "Replacement or service interval: every 40,000 km or every 24 months.\n"
    "Notes: Brake fluid absorbs moisture over time regardless of distance driven. "
    "Replace on time even if the car is barely used.\n"
    "Typical workshop time: 45 minutes.",
}


@pytest.fixture(autouse=True)
def cold_cache():
    """Every test starts with the library unread, and leaves it that way."""
    library._LIBRARY.clear()
    yield
    library._LIBRARY.clear()


def tsb(section, text, page=1, number="TSB-010"):
    return {
        "doc_type": "bulletin",
        "source_file": f"{number}.pdf",
        "section": section,
        "page": page,
        "content": f"[{number}, section {section}] {text}",
    }


HEADER = tsb(
    "HEADER",
    "SERVICE BULLETIN TSB-010 Corvale S1 1.2L petrol — clutch pedal feeling spongy SYNTHETIC DOCUMENT. "
    "Generated by a language model for a portfolio project. Not a real bulletin.",
)


def test_a_fault_code_is_read_back_into_fields():
    c = library.fault_code(DTC)
    assert c["code"] == "P0420"
    assert c["system"] == "Powertrain"
    assert c["title"] == "Catalyst System Efficiency Below Threshold (Bank 1)"
    assert c["meaning"].startswith("The catalytic converter")
    assert c["causes"].endswith("for a long time")
    assert c["severity"] == "medium"
    assert c["safe_to_drive"] == "yes-with-care"


def test_the_citation_shown_matches_what_the_agent_writes():
    """The Library shows how the assistant cites each document, so it has to
    match retrieval.Chunk.citation() exactly."""
    assert library.fault_code(DTC)["cite_as"] == "fault code list, P0420"
    assert library.maintenance_item(MAINT)["cite_as"] == "maintenance schedule, Brake fluid"
    b = library.bulletins([HEADER, tsb("SYMPTOMS", "Pedal feels soft.")])[0]
    assert b["sections"][0]["cite_as"] == "TSB-010, Symptoms"


def test_a_maintenance_item_is_read_back_into_fields():
    m = library.maintenance_item(MAINT)
    assert m["item"] == "Brake fluid"
    assert m["interval"] == "every 40,000 km or every 24 months"
    assert m["notes"].startswith("Brake fluid absorbs moisture")
    assert m["workshop_minutes"] == 45


def test_a_bulletin_gets_its_number_vehicle_and_topic_from_the_header():
    b = library.bulletins([HEADER, tsb("SUMMARY", "A summary.")])[0]
    assert b["number"] == "TSB-010"
    assert b["vehicle"] == "Corvale S1 1.2L petrol"
    assert b["topic"] == "clutch pedal feeling spongy"


def test_the_header_is_not_shown_as_a_section():
    b = library.bulletins([HEADER, tsb("SUMMARY", "A summary.")])[0]
    assert [s["name"] for s in b["sections"]] == ["Summary"]


def test_sections_come_out_in_bulletin_order_whatever_order_the_index_returns():
    pieces = [
        tsb("WARRANTY INFORMATION", "w", page=2),
        tsb("SYMPTOMS", "s"),
        HEADER,
        tsb("SUMMARY", "a"),
        tsb("PARTS REQUIRED", "p", page=2),
    ]
    names = [s["name"] for s in library.bulletins(pieces)[0]["sections"]]
    assert names == ["Summary", "Symptoms", "Parts Required", "Warranty Information"]


def test_the_piece_label_is_stripped_from_section_text():
    b = library.bulletins([HEADER, tsb("SYMPTOMS", "Pedal feels soft.")])[0]
    assert b["sections"][0]["text"] == "Pedal feels soft."


def test_an_unknown_section_is_kept_not_dropped():
    b = library.bulletins([HEADER, tsb("SUMMARY", "a"), tsb("TORQUE SPECIFICATIONS", "t", page=2)])[0]
    assert [s["name"] for s in b["sections"]] == ["Summary", "Torque Specifications"]


def test_a_section_split_across_pieces_is_shown_as_one():
    b = library.bulletins([HEADER, tsb("REPAIR PROCEDURE", "first half"), tsb("REPAIR PROCEDURE", "second half")])[0]
    assert len(b["sections"]) == 1
    assert "first half" in b["sections"][0]["text"] and "second half" in b["sections"][0]["text"]


def test_a_bulletin_without_a_readable_header_still_appears():
    b = library.bulletins([tsb("SUMMARY", "a", number="TSB-031")])[0]
    assert b["number"] == "TSB-031"
    assert b["topic"] == ""


def test_build_groups_counts_and_sorts():
    pieces = [
        HEADER,
        tsb("SUMMARY", "a"),
        tsb("SUMMARY", "b", number="TSB-002"),
        DTC,
        {**DTC, "section": "P0010", "content": DTC["content"].replace("P0420", "P0010")},
        MAINT,
    ]
    lib = library.build(pieces)
    assert lib["counts"] == {"fault_codes": 2, "maintenance": 1, "bulletins": 2, "pieces": 6}
    assert [c["code"] for c in lib["fault_codes"]] == ["P0010", "P0420"]
    assert [b["number"] for b in lib["bulletins"]] == ["TSB-002", "TSB-010"]


def test_load_is_cached(monkeypatch):
    calls = []

    def fetch_all(fields, top=1000):
        calls.append((fields, top))
        return [DTC, MAINT, HEADER]

    monkeypatch.setattr(library.retrieval, "fetch_all", fetch_all)

    first = library.load()
    second = library.load()
    assert first is second
    assert len(calls) == 1
    assert first["counts"]["bulletins"] == 1


# ------------------------------------------------- the cache under concurrent readers


class SearchDown(Exception):
    """What the fake search raises. Not a RuntimeError, because a broken
    barrier is one, and a failure test must not pass on the wrong error."""


def _fetch_together(readers, fail=False):
    """Stand-in for the Azure Search call load() makes when the cache is cold.

    No call returns until `readers` of them are inside at once. A real fetch is
    entirely waiting on Azure, so what matters is whether several readers can be
    on the wire at the same time or each sits behind the one ahead, holding a
    threadpool thread. If a lock spanned the fetch the barrier could never fill:
    it times out, and every reader gets BrokenBarrierError instead of an answer.
    """
    barrier = threading.Barrier(readers, timeout=5)
    calls = []

    def fetch_all(fields, top=1000):
        calls.append(1)
        barrier.wait()
        if fail:
            raise SearchDown("search is down")
        return [DTC, MAINT, HEADER]

    fetch_all.calls = calls
    return fetch_all


def _load_concurrently(n):
    """n threads into load() at once. Returns what each got - a dict or the
    exception it raised."""
    out = []

    def one():
        try:
            out.append(library.load())
        except Exception as e:  # noqa: BLE001
            out.append(e)

    threads = [threading.Thread(target=one) for _ in range(n)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    return out


def test_the_search_runs_outside_the_lock(monkeypatch):
    """/library is a sync endpoint, so each reader holds one of Starlette's 40
    threadpool threads for as long as load() takes, and /health - also sync -
    queues behind whatever is left. While the lock spanned the search, readers
    could only ever be on the wire one at a time; the barrier fills only if all
    eight are searching together."""
    monkeypatch.setattr(library.retrieval, "fetch_all", _fetch_together(8))

    results = _load_concurrently(8)

    assert all(isinstance(r, dict) for r in results), f"the readers queued: {results[0]!r}"
    assert all(r["counts"]["bulletins"] == 1 for r in results)


def test_a_failed_fetch_is_not_paid_for_n_times(monkeypatch):
    """The outage this guards against, and the reason the lock had to go.

    A replica that has just scaled from zero has a cold cache, and Azure Search
    is Free tier with no SLA. With the search inside the lock, a fetch that
    failed released the lock to the next reader, which started its own full
    attempt from the front of the queue: six readers cost six fetches end to
    end, not one. azure_http retries a 5xx up to three times at up to 20s, so
    each of those attempts is worth up to a minute of a held thread. The
    threadpool empties, /health cannot get a thread, the Dockerfile HEALTHCHECK
    fails its three 4s tries, and the container is restarted - because people
    looked at the document list.

    Six readers still make six fetches, but side by side: the barrier opens
    only when all six are on the wire together.
    """
    monkeypatch.setattr(library.retrieval, "fetch_all", _fetch_together(6, fail=True))

    results = _load_concurrently(6)

    # Every reader gets the search's own error - /library answers 503, it does
    # not hang - and not a broken barrier, which would mean they queued.
    assert all(isinstance(r, SearchDown) for r in results), f"the readers queued: {results[0]!r}"


def test_the_burst_still_leaves_the_library_cached(monkeypatch):
    """Racing readers may each pay for a search - that is the trade the lock
    stopped making - but the last one to finish must still fill the cache, or
    every page view afterwards would search again."""
    fetch = _fetch_together(4)
    monkeypatch.setattr(library.retrieval, "fetch_all", fetch)

    _load_concurrently(4)
    during_burst = len(fetch.calls)
    library.load()
    assert len(fetch.calls) == during_burst, "the burst left nothing cached"
